apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-jsj6
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pcdw-tenant/rhtap-demo-app/hacbs-test-project-jsj6@sha256:40ba7fc0608ade893005bb3ccc105aac1f9a4751bc1540482fc1b8276e09e474
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
